### ISSUE TITLE
Advanced - Animation

### ISSUE THREAD

**Issue by asimnyz** [surf-visualization/blender-course#3]
When executing the script "1. import ply files" in the "Flipbook animation - 💻 Using Python to set up an animated mesh" section, the following error occurs:

Error: Python: Traceback (most recent call last):
  File "/home/lissai/Desktop/SURF_2024AdvCourse/course-data/data/advanced/animation/animated_ply_imports.blend/1. import ply files", line 32, in <module>
  File "/home/lissai/Desktop/blender-4.1.1-linux-x64/4.1/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.import_mesh.ply" error, could not be found

**Comment by paulmelis** [comment]
Thanks for the report. This seems to be a case of me forgetting to update the blend file on the SURFdrive share, as I had already fixed this locally. A different Python call is needed with newer versions of Blender. 

Can you try the updated `animated_ply_imports.blend` from the SURFdrive share?

**Comment by asimnyz** [comment]
Now it's working fine. Thank you very much!
